update unknown

diff --git a/slugify-files b/slugify-files
--- a/slugify-files
+++ b/slugify-files
@@ -2,22 +2,27 @@
 #shellcheck disable=SC1091
 # slug-files - Batch rename files to URL/filename-friendly slugs
 set -euo pipefail
+shopt -s inherit_errexit shift_verbose extglob nullglob
 
-declare -r SCRIPT_PATH=$(realpath -e -- "$0")
-declare -r SCRIPT_NAME=$(basename -- "$SCRIPT_PATH")
-declare -r SCRIPT_DIR=$(dirname -- "$SCRIPT_PATH")
+declare -r VERSION=1.0.0
+#shellcheck disable=SC2155
+declare -r SCRIPT_PATH=$(realpath -- "$0")
+declare -r SCRIPT_DIR=${SCRIPT_PATH%/*} SCRIPT_NAME=${SCRIPT_PATH##*/}
 
 declare -i VERBOSE=1
 
-usage() {
-  echo "$SCRIPT_NAME [-s|--sep_char CHAR] [-m|--max-len LEN] [-p|--preserve-case] [-n|--no-clobber] [-q|--quiet] file [file...]"
-  echo "Rename files to post-slug format"
-  echo "eg, $SCRIPT_NAME -pn /a/directory/*.txt"
-  exit
+show_help() {
+  cat <<HELP
+Usage: $SCRIPT_NAME [-s|--sep_char CHAR] [-m|--max-len LEN] [-p|--preserve-case] [-n|--no-clobber] [-q|--quiet] file [file...]
+
+Rename files to post-slug format
+
+eg: $SCRIPT_NAME -pn /a/directory/*.txt
+HELP
 }
 
-info() { >&2 echo "$SCRIPT_NAME:" "${1:-}"; >&2 echo; }
-die() { >&2 echo "$SCRIPT_NAME:" 'error:' "${2:-}"; exit "${1:-1}"; }
+info() { >&2 echo "$SCRIPT_NAME:" "$1"; >&2 echo; }
+die() { >&2 echo "$SCRIPT_NAME:" 'error:' "$2"; exit "$1"; }
 
 declare -a Files=()
 declare -- sep_char='-'
@@ -36,7 +41,7 @@ while (($#)); do case $1 in
       ;;
   -m|--max-len)
       shift
-      max_len="${1:-0}"
+      max_len=${1:-0}
       if ((max_len>255)); then
         max_len=255
       fi
@@ -44,13 +49,18 @@ while (($#)); do case $1 in
         max_len=0
       fi
       ;;
-  -p|--preserve-case) preserve_case=1 ;;
-  -n|--no-clobber) clobber=0 ;;
-  -v|--verbose) VERBOSE=1 ;;
-  -q|--quiet) VERBOSE=0 ;;
-  -h|--help) usage ;;
-  -[smpnvqh]*) #shellcheck disable=SC2046 #split up single options
-      set -- '' $(printf -- "-%c " $(grep -o . <<<"${1:1}")) "${@:2}" ;;
+  -p|--preserve-case)
+      preserve_case=1 ;;
+  -n|--no-clobber)
+      clobber=0 ;;
+  -v|--verbose)
+      VERBOSE=1 ;;
+  -q|--quiet)
+      VERBOSE=0 ;;
+  -h|--help)
+      show_help; exit 0 ;;
+  -[smpnvqh]*) #split up single options
+      set -- "${1:0:2}" "-${1:2}" "${@:2}"; continue ;;
   -*) die 22 "Invalid option ${1@Q}" ;;
   *)  Files+=("$1") ;;
 esac; shift; done
@@ -64,11 +74,11 @@ read -rp "$SCRIPT_NAME: Proceed? y/n "; [[ $REPLY == y ]] || exit 1
 for file in "${Files[@]}"; do
   file=$(realpath -e -- "$file")
   dirname=$(dirname -- "$file")
-  newfile=$(basename "$file")
+  newfile=$(basename -- "$file")
   ext=''
   if [[ $newfile == *"."* ]]; then
     ext=".${newfile##*.}"
-    newfile=$(basename -s "$ext" "$newfile")
+    newfile=$(basename -s "$ext" -- "$newfile")
   fi
 
   slug=$(post_slug "$newfile" "$sep_char" "$preserve_case" "$max_len")
@@ -76,7 +86,7 @@ for file in "${Files[@]}"; do
     info "WARNING: Zero length slug for ${file@Q}"
     continue
   fi
-  newfile="$dirname"/"$slug$ext"
+  newfile="$dirname/$slug$ext"
 
   if [[ $newfile == "$file" ]]; then
     ((!VERBOSE)) || info "No change required for ${file@Q}"
